name: Test Donut Falls flye assembly

on: [pull_request, workflow_dispatch]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
            
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
          
      - name: Run Donut Falls
        run: |
          docker --version
          
          nextflow run . -profile docker,test \
            -c .github/workflows/github_actions.config

          tree donut_falls

      - name: Check files
        run: |
          ls  donut_falls/multiqc/multiqc_report.html
          ls  donut_falls/summary/flye_assembly_info.txt
          ls  donut_falls/df/flye/assembly.fasta donut_falls/df/flye/assembly_graph.gfa
          cat donut_falls/summary/donut_falls_summary.json
